# Uncomment the next line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '12.0'

target 'PlanMaster' do
  pod 'GooglePlaces', '6.1.1'
  pod 'GoogleMaps', '6.1.1'
end